/*===========================================================================*/
/*                                                                           *
 * Copyright (c) 2020, Computer Graphics Group RWTH Aachen University        *
 *                            All rights reserved                            *
 *                                                                           *
 * Basic Techniques in Computer Graphics Exercise                            *
 *                            DO NOT EDIT THIS FILE!                         *
 *                                                                           */
/*===========================================================================*/

#pragma once


// OpenGL Math:
#include <glm/glm.hpp>

// draws a circle of radius 1.0 (screen is from -1..1) with a given transform and color (RGB)
void drawCircle(const glm::vec3& color, const glm::mat4& model, const glm::mat4& view, const glm::mat4& projection);

extern bool arrowKeyUpPressed;
extern bool arrowKeyLeftPressed;
extern bool arrowKeyRightPressed;
extern bool arrowKeyDownPressed;
