/*===========================================================================*/
/*                                                                           *
 * Copyright (c) 2020, Computer Graphics Group RWTH Aachen University        *
 *                            All rights reserved                            *
 *                                                                           *
 * Basic Techniques in Computer Graphics Exercise                            *
 *                            DO NOT EDIT THIS FILE!                         *
 *                                                                           */
/*===========================================================================*/

#pragma once

#include <glad/glad.h>
/// make sure inclusion of glad.h does not come after glfw

#include <GLFW/glfw3.h>

// OpenGL Math:
#define GLM_SWIZZLE_RGBA
#include <glm/glm.hpp>


class Sphere
{
public:
    Sphere(unsigned int detail = 8);
    ~Sphere();

    void draw();

private:
    glm::vec3 positionOnSphere(int sliceNumber, int stackNumber);

    void addTriangle(unsigned int sl0, unsigned int st0, unsigned int sl1, unsigned int st1, unsigned int sl2, unsigned int st2, unsigned int& posOffset);

    unsigned int stacks;
    unsigned int slices;
    unsigned int vertexCount;
    unsigned int elementCount;
    GLuint arrayBuffer;
    float* vertexData;
    float radius;
    bool uploadedDataToGPU;
};
