/*===========================================================================*/
/*                                                                           *
 * Copyright (c) 2020, Computer Graphics Group RWTH Aachen University        *
 *                            All rights reserved                            *
 *                                                                           *
 * Basic Techniques in Computer Graphics Exercise                            *
 *                            DO NOT EDIT THIS FILE!                         *
 *                                                                           */
/*===========================================================================*/

#pragma once

#include "constants.hh"
#include "common.hh"

namespace task
{
void drawScene(int scene, float runTime);
void initCustomResources();
void deleteCustomResources();
}

namespace solution
{
void drawScene(int scene, float runTime);
void initCustomResources();
void deleteCustomResources();
}
